baseURL = "/"
languageCode = "en-us"
title = "RabbitControl"
theme = "kube"
description = "A binary data-format definition to describe data values and user interface elements."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "the rabbits" # add your company name
  github = "https://github.com/rabbitControl" # add your github profile name
  mastodon = "https://vis.social/@rabbitcontrol" # add your twitter profile
  email = ""

[[menu.main]]
    name = "Applications"
    weight = -200
    url = "/apps/"
[[menu.main]]
    name = "Libraries"
    weight = -100
    url = "/libs/"
[[menu.main]]
    name = "FAQs"
    weight = -50
    url = "/faq/"
[[menu.main]]
    name = "Available for"
    weight = 40
    url = "/platforms/"
[[menu.main]]
    name = "Contact"
    weight = 50
    url = "/contact/"
[[menu.main]]
    hrefTargetBlank = false
    name = "Rabbithole"
    weight = 100
    url = "https://rabbithole.rabbitcontrol.cc"
