baseURL = "/"
languageCode = "en-us"
title = "RabbitControl"
theme = "kube"
description = "A binary data-format definition to describe data values and user interface elements."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "the rabbits" # add your company name
  github = "https://github.com/rabbitControl" # add your github profile name
  mastodon = "https://vis.social/@rabbitcontrol" # add your twitter profile
  email = ""

[[menu.main]]
    name = "Carrots"
    weight = -200
    url = "/clients/"
[[menu.main]]
    name = "Developers"
    weight = -100
    url = "/developers/"
[[menu.main]]
    name = "FAQ"
    weight = -50
    url = "/faq/"
