name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false  # don't fetch Hugo themes
          fetch-depth: 1    # don't fetch all history to save time

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: rabbitcontrol/rabbitcontrol.github.io
          publish_dir: ./public
          publish_branch: master  # deploying branch
          
      #deploy to rcp.vvvv.org
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: root
          server: 78.47.109.137
          #port: # default is 22
          # you can copy private_key from your *.pem file, keep format
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # will put all file under this path
          local_path: ./static/client/* # default is ./*
          # files will copy to under remote_path
          remote_path: /var/www-rcp # default is /
          # sftp args
          # args: # optional:  
