name: deploy website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false  # don't fetch Hugo themes
          fetch-depth: 1    # don't fetch all history to save time

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          # extended: true

      - name: Build
        run: hugo --minify

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     personal_token: ${{ secrets.PERSONAL_TOKEN }}
      #     external_repository: rabbitcontrol/rabbitcontrol.github.io
      #     publish_dir: ./public
      #     publish_branch: master  # deploying branch

      - name: FTP Deploy
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: rabbitcontrol.cc
          user: ${{ secrets.RABBITCONTROL_CC_FTP_U }}
          password: ${{ secrets.RABBITCONTROL_CC_FTP_P }}
          localDir: "public"
          remoteDir: "www"
